name: Integration build
on: 
  workflow_dispatch:
    inputs:
      component_repo:
        description: 'component repo'     
        required: true
        default: 'wso2/carbon-apimgt'
      component_branch:
        description: 'Component branch Name'     
        required: true
        default: 'master'
      product_repo:
        description: 'product repo'     
        required: true
        default: 'wso2/product-apim'
      product_branch:
        description: 'Product branch Name'     
        required: true
        default: 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: 1
            segment: group1
          - id: 2
            segment: group2
          - id: 3
            segment: group3
          - id: 4
            segment: group4
      fail-fast: false
    steps:
    - name: Run hostname
      run: hostname
    - name: Fix host entry
      run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
    - name: Show hosts
      run: cat /etc/hosts
    - name: Checkout module-refactor
      uses: actions/checkout@v2
      with: 
        repository: ${{ github.event.inputs.component_repo }}
        ref: refs/heads/${{ github.event.inputs.component_branch }}
        path: carbon-apimgt
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11.0.16+8
        distribution: 'temurin'
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build carbon-apimgt with Test.
      run: mvn clean install -Dmaven.test.skip=true --file carbon-apimgt/pom.xml
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version -q --file carbon-apimgt/pom.xml -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    - name: Checkout Product-APIM
      uses: actions/checkout@v2
      with: 
        repository: ${{ github.event.inputs.product_repo }}
        ref: refs/heads/${{ github.event.inputs.product_branch }}
        path: product-apim
    - name: Build Product-Apim with Maven
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file product-apim/pom.xml -DskipBenchMarkTest=true
      env:
        PRODUCT_APIM_TEST_GROUPS: ${{ matrix.segment }}
    - name: Prepare upload testng report
      if: always()
      run: mv product-apim/modules/integration/tests-integration/tests-backend/target/surefire-reports/TEST-TestSuite.xml TEST-TestSuite_${{ matrix.id }}.xml
    - name: Archive testng report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TEST-TestSuite_${{ matrix.id }}
        path: |
          TEST-TestSuite_${{ matrix.id }}.xml
        if-no-files-found: warn
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: Build
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()
  show-report:
    if: always()
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: reports
      - name: Publish Test Report
        if: always()
        uses: malinthaprasan/action-surefire-report@v1
        with:
          report_paths: 'reports/**/TEST-*.xml'
  run-benchmark-test:
    runs-on: ubuntu-latest
    steps:
    - name: Run hostname
      run: hostname
    - name: Fix host entry
      run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
    - name: Show hosts
      run: cat /etc/hosts
    - name: Checkout module-refactor
      uses: actions/checkout@v2
      with: 
        repository: ${{ github.event.inputs.component_repo }}
        ref: refs/heads/${{ github.event.inputs.component_branch }}
        path: carbon-apimgt

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11.0.16+8
        distribution: 'temurin'
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build carbon-apimgt with Test.
      run: mvn clean install --file carbon-apimgt/pom.xml -Dmaven.test.skip=true
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version --file carbon-apimgt/pom.xml -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    - name: Checkout Product-APIM
      uses: actions/checkout@v2
      with: 
        repository: ${{ github.event.inputs.product_repo }}
        ref: refs/heads/${{ github.event.inputs.product_branch }}
        path: product-apim
    - name: Build Product-Apim with Maven
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file product-apim/pom.xml -DskipIntegrationTests=true
