name: Integration build
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout eventbased-gw
      uses: actions/checkout@v1
      with: 
        repository: tharindu1st/carbon-apimgt
        ref: refs/heads/fix

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          java-build

    - name: Build carbon-apimgt with Test.
      run: mvn clean install --file pom.xml
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    - name: Checkout Product-APIM
      uses: actions/checkout@v1
      with: 
        repository: tharindu1st/product-apim
        ref: refs/heads/proxt-api-removal
    - name: Build Product-Apim with Maven
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file ../product-apim/pom.xml
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: Build
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()
