name: Test Build

on: 
  workflow_dispatch:
    inputs:
      component_repo_owner:
        description: 'Owner Of component repo'     
        required: true
        default: 'wso2'
      component_branch:
        description: 'Component branch Name'     
        required: true
        default: 'master'
      product_repo_owner:
        description: 'Owner Of product repo'     
        required: true
        default: 'wso2'
      product_branch:
        description: 'Product branch Name'     
        required: true
        default: 'master'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Component Repo owner: ${{ github.event.inputs.component_repo_owner }}" 
        echo "Component Repo Branch: ${{ github.event.inputs.component_branch }}" 
        echo "Product Repo Owner: ${{ github.event.inputs.product_repo_owner }}" 
        echo "Product Repo Branch: ${{ github.event.inputs.product_branch }}" 
